#!/usr/bin/env bash
# Delete everything created by scripts/deploy.sh: the resource group (agents, indexes, blobs, models...)
# and purge the Foundry account, which otherwise remains soft-deleted for 48 h and retains model quota.
#
# Usage: ./scripts/destroy.sh [--yes]
# Takes the resource group from RESOURCE_GROUP or, if unset, from the .env generated by deploy.sh.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

env_value() {
  if [ -f .env ]; then
    grep -E "^$1=" .env | head -1 | cut -d= -f2- | sed -e 's/^"//' -e 's/"$//' || true
  fi
}

RESOURCE_GROUP="${RESOURCE_GROUP:-$(env_value AZURE_RESOURCE_GROUP)}"
RESOURCE_GROUP="${RESOURCE_GROUP:-rg-foundry-docs-runtime}"
SUBSCRIPTION_ID="${AZURE_SUBSCRIPTION_ID:-$(env_value AZURE_SUBSCRIPTION_ID)}"
SUBSCRIPTION_ID="${SUBSCRIPTION_ID:-$(az account show --query id -o tsv)}"
AZD_DEFAULT_ENV=""
if [ -f .azure/config.json ]; then
  AZD_DEFAULT_ENV="$(sed -n 's/.*"defaultEnvironment": *"\([^"]*\)".*/\1/p' .azure/config.json)"
fi
AZD_ENV_NAME="${AZD_ENV_NAME:-${AZD_DEFAULT_ENV:-docs-poc}}"

if [ "$(az group exists --subscription "$SUBSCRIPTION_ID" -n "$RESOURCE_GROUP")" != "true" ]; then
  echo "Resource group $RESOURCE_GROUP does not exist in subscription $SUBSCRIPTION_ID: nothing to delete."
  exit 0
fi

echo "Resources in $RESOURCE_GROUP:"
az resource list --subscription "$SUBSCRIPTION_ID" -g "$RESOURCE_GROUP" --query "[].{name:name, type:type}" -o table
if [ "${1:-}" != "--yes" ]; then
  printf '\nDelete resource group %s and all its contents? [y/N] ' "$RESOURCE_GROUP"
  read -r answer
  case "$answer" in
    y | Y | yes | YES) ;;
    *)
      echo "Canceled."
      exit 1
      ;;
  esac
fi

# Foundry accounts in the group (name and region) to purge after deletion.
ACCOUNTS="$(az cognitiveservices account list --subscription "$SUBSCRIPTION_ID" -g "$RESOURCE_GROUP" --query "[].[name, location]" -o tsv)"

echo "Deleting $RESOURCE_GROUP (a few minutes)..."
az group delete --subscription "$SUBSCRIPTION_ID" -n "$RESOURCE_GROUP" --yes

if [ -n "$ACCOUNTS" ]; then
  while read -r name location; do
    [ -n "$name" ] || continue
    echo "Purging account $name ($location) to release its name and model quota..."
    az cognitiveservices account purge --subscription "$SUBSCRIPTION_ID" -g "$RESOURCE_GROUP" -n "$name" -l "$location" ||
      echo "  warning: could not purge $name; do it from the portal (Foundry > deleted resources)."
  done <<EOF
$ACCOUNTS
EOF
fi

# Local state that points to the deleted resources.
if [ "$(env_value AZURE_RESOURCE_GROUP)" = "$RESOURCE_GROUP" ]; then
  rm -rf ".azure/deploy" ".azure/$AZD_ENV_NAME" .env
  if [ "$AZD_DEFAULT_ENV" = "$AZD_ENV_NAME" ]; then rm -f .azure/config.json; fi
  echo "Local state deleted (.env, .azure/$AZD_ENV_NAME)."
fi
echo "Done."
